apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc-2
provisioner: nfs-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"