apiVersion: apps/v1
kind: Deployment
metadata:
  name:  blog-web
  namespace: default
  labels:
    type:  web
spec:
  selector:
    matchLabels:
      app: blog-web
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-web
    spec:
      containers:
        - name:  blog-web
          image:  nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 50m

---
apiVersion: v1
kind: Service
metadata:
  name: blog-web-svc
  namespace: default
spec:
  selector:
    app: blog-web
  type: ClusterIP
  ports:
    - name: blog-web-svc
      port: 80
      targetPort: 80
      protocol: TCP