kind: Deployment   #定义Deployment
apiVersion: apps/v1   #版本
metadata:    #定义元数据
  name: deploy-mysql-volume   #Deployment名称为deploy-mysql
  namespace: test-ns   #使用的名称空间为test-ns
  labels:    #为Deployment设置标签
    name: deploy-mysql-volume
    type: deployment
spec:    ##设置期望状态  规约
  replicas: 2   #只存在一个副本
  selector:
    matchLabels:
      type: pod-mysql2
  template:   #标准末班
    metadata:
      name: pod-mysql2
      namespace: test-ns
      labels:
        type: pod-mysql2
    spec:   #规约，期望状态
      volumes:
        - name: mysql-volume1    #必须要和deploy.spec.template.spec.containers.volumeMounts.name保持一致
          secret:
            secretName: secret-mysql-properties  #指定已存在的secriet名称
            items:
              - key: dev-application.yaml   #secret-mysql-properties里的key
                path: dev-application.yml   #挂载到容器里后放在指定目录/app，文件重命名维dev-application.yml
              - key: test-application.yaml
                path: test-application.yml
      containers:
        - name: pod-mysql2-volume   #给mysql容器起一个名字
          image: mysql:8.0.29   #使用mysql:8.0.29镜像
          imagePullPolicy: IfNotPresent   #如果本地存在该镜像，那么不从远程仓库拉取该镜像
          env:   #设置mysql容器环境变量
            - name: MYSQL_ROOT_PASSWORD    #root用户的密码
              valueFrom:
                secretKeyRef:
                  name: secret-mysql   #secret名字
                  key: mysql_root_password   #secret-mysql下的key
            - name: MYSQL_USER    #自定义用户名
              valueFrom:
                secretKeyRef:
                  name: secret-mysql   #secret名字
                  key: mysql_user   #自定义用户名
            - name: MYSQL_PASSWORD    #自定义用户名的密码
              valueFrom:
                secretKeyRef:
                  name: secret-mysql   #secret名字
                  key: mysql_password  #自定义用户名的密码
          ports:  #暴露mysql端口
            - containerPort: 13306
          volumeMounts:
            - mountPath: /app   #挂载到容器内部/app目录下
              name: mysql-volume1

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
  namespace: test-ns
data:
  mysql_root_password: MXFhejJ3c3gh   #   mysql数据库root用户密码  Base64加密后的内容
  mysql_user: Y2xfdGVzdG1vbQ==   #  mysql自定义的用户
  mysql_password: MXFhejJ3c3gh  #  mysql自定义的用户的密码

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql-properties
  namespace: test-ns
data:
  dev-application.yaml: MXFhejJ3c3gh   #   mysql数据库root用户密码  Base64加密后的内容
  test-application.yaml: Y2xfdGVzdG1vbQ==   #  mysql自定义的用户
  prod-application.yaml: MXFhejJ3c3gh  #  mysql自定义的用户的密码