apiVersion: v1
kind: Secret
metadata:
  name: secret-clmysql-yaml
  namespace: test-ns
data:
  dev-application.yaml: |
    dXJsOiBsb2NhbGhvc3Q6MzMwNgp1c2VybmFtZTogcm9vdApwYXNzd29yZDogMXFhejJ3c3gh
  test-application.yaml: |
    dXJsOiAxOTIuMTY4LjEyLjUyOjEzMzA2CnVzZXJuYW1lOiByb290CnBhc3N3b3JkOiAxcWF6MndzeCE=
  prod-application.yaml: |
    dXJsOiAxOTIuMTY4LjEyLjUzOjEzMzA2CnVzZXJuYW1lOiByb290CnBhc3N3b3JkOiAxcWF6MndzeCE=