kind: Deployment   #定义Deployment
apiVersion: apps/v1   #版本
metadata:    #定义元数据
  name: deploy-mysql-configmap   #Deployment名称为deploy-mysql
  namespace: test-ns   #使用的名称空间为test-ns
  labels:    #为Deployment设置标签
    name: deploy-mysql-configmap
    type: deployment
spec:    ##设置期望状态  规约
  replicas: 2   #只存在一个副本
  selector:
    matchLabels:
      type: pod-mysql2-configmap   #选中pod的lables标签属性值
  template:   #标准末班
    metadata:
      name: pod-mysql2-configmap
      namespace: test-ns
      labels:
        type: pod-mysql2-configmap
    spec:   #规约，期望状态
      containers:
        - name: pod-mysql2-configmap-secret   #给mysql容器起一个名字
          image: mysql:8.0.29   #使用mysql:8.0.29镜像
          imagePullPolicy: IfNotPresent   #如果本地存在该镜像，那么不从远程仓库拉取该镜像
          env:   #设置mysql容器环境变量
            - name: MYSQL_ROOT_PASSWORD    #root用户的密码
              valueFrom:
                secretKeyRef:
                  name: secret-mysql   #secret名字
                  key: mysql_root_password   #secret-mysql下的key
            - name: MYSQL_USER    #自定义用户名
              valueFrom:
                configMapKeyRef:
                  name: configmap-mysql   # configmap名字
                  key: mysql_user   # configmap的key值
            - name: MYSQL_PASSWORD    #自定义用户名的密码
              valueFrom:
                secretKeyRef:
                  name: secret-mysql   #secret名字
                  key: mysql_password  #自定义用户名的密码
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap-mysql   #  configmap名字
                  key: mysql_database   # 指定的configmap下的key值
          ports:  #暴露mysql端口
            - containerPort: 13306

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
  namespace: test-ns
data:
  mysql_root_password: MXFhejJ3c3gh   #   mysql数据库root用户密码  Base64加密后的内容
  mysql_password: MXFhejJ3c3gh  #  mysql自定义的用户的密码，对应的configmap的mysql_user

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-mysql
  namespace: test-ns
data:
  mysql_user: test1   # mysql自定义用户名
  mysql_database: cl_testmom   #指定mysql的数据库名