kind: Deployment
apiVersion: apps/v1
metadata:
  name: canary-deployv2
  namespace: test-ns
  labels:
    app: canary-deployv2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: canary-nginx
      version: v2222
  template:
    metadata:
      labels:
        app: canary-nginx
        version: v2222
    spec:
      containers:
        - name: nginx-v2
          image: nginx
          ports:
            - containerPort: 80