kind: Service
apiVersion: v1
metadata:
  name: canary-service-v1
  namespace: blog
  labels:
    app: canary-service-v1
    name: canary-service-v1
spec:
  selector:
    app: canary-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30666
  type: NodePort