kind: Deployment
apiVersion: apps/v1
metadata:
  name: canary-deployv1
  namespace: test-ns
  labels:
    app: canary-deployv1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-nginx
      version: v1111
  template:
    metadata:
      labels:
        app: canary-nginx
        version: v1111
    spec:
      containers:
        - name: nginx-v1
          image: nginx
          ports:
            - containerPort: 80