kind: Job
apiVersion: batch/v1
metadata:
  name: job-test01
  namespace: test-ns
  labels:
    app: job-test01
spec:
  completions: 10   #需要完成10次任务
  parallelism: 3   #一次并行启动3个任务
  template:
    metadata:
      labels:
        app: busybox-test
    spec:
      containers:
        - name: centos
          image: centos
          command: ["/bin/bash", "-c", "ping -c 5 baidu.com"]
      restartPolicy: Never   #永远都不重新启动