apiVersion: v1
kind: PersistentVolumeClaim    #持久卷申请
metadata:
  name: pvc-nginx
  namespace: blog
  labels:
    name: pvc-nginx-nfs-sc
spec:
  storageClassName: nfs-sc-0   # 指定sc名称 这里storageClass动态分配创建pv
  accessModes:
    - ReadWriteMany   #允许多个回话读写
  resources:
    requests:
      storage: 50Mi   # pvc申请资源大小

---
kind: Service
apiVersion: v1
metadata:
  name: service-nginx-pvc-nfs-sc
  namespace: blog
spec:
  selector:
    type: pod-pvc-nfs-sc   #根据标签命中的pod
  type: ClusterIP   #ExternalName, ClusterIP, NodePort, and LoadBalancer
  ports:
    - name: service-nginx-pvc-nfs-sc
      port: 80   #集群端口
      targetPort: 80   #映射到pod内部端口

---
kind: Deployment   #定义Deployment
apiVersion: apps/v1   #版本
metadata:    #定义元数据
  name: deploy-volume-pvc-nfs-sc   #Deployment名称为deploy-volume-pvc-nfs-sc
  namespace: blog   #使用的名称空间为blog
  labels:    #为Deployment设置标签
    name: deploy-volume-pvc-nfs-sc
    type: deploy
spec:    ##设置期望状态  规约
  replicas: 2   #存在两个副本
  selector:
    matchLabels:
      type: pod-pvc-nfs-sc   #选中标签为pod-pvc-nfs-sc的pod
  template:   #标准
    metadata:
      name: pod-pvc-nfs-sc
      namespace: blog
      labels:
        type: pod-pvc-nfs-sc   # 声明pod的标签
    spec:   #规约，期望状态
      containers:
        - name: pod-nginx-volume-pvc-nfs   #给nginx容器起一个名字
          image: nginx   #使用nginx最新镜像
          imagePullPolicy: IfNotPresent   #如果本地存在该镜像，那么不从远程仓库拉取该镜像
          ports:  #暴露mnginx端口
            - containerPort: 80
          volumeMounts:
            - name: clmom-html-storage
              mountPath: /usr/share/nginx/html/   #指明挂载容器的指定目录
      volumes:
        - name: clmom-html-storage   #与volumeMounts指定的name值相同
          persistentVolumeClaim:
            claimName: pvc-nginx   #对应pvc的name值