kind: Service
apiVersion: v1
metadata:
  name: service-clusterip-test2
  namespace: test-ns
spec:
  selector:
    app: canary-nginx   #根据标签命中的pod
  clusterIP: 10.96.10.11   #可以在svc规定的IP范围内指定IP，也可以设置为None，即headless service无头服务
  type: ClusterIP   #ExternalName, ClusterIP, NodePort, and LoadBalancer
  ports:
    - name: nginx-service
      port: 80   #集群端口
      targetPort: 80   #映射到pod内部端口